name: sounds_interesting
channels:
  - pytorch
  - anaconda
  - nvidia
  - defaults
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2023.01.10
  - certifi=2023.5.7
  - cffi=1.15.1
  - colorama=0.4.6
  - comm=0.1.2
  - cryptography=39.0.1
  - cuda-cccl=12.1.55
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.1.55
  - cuda-runtime=11.8.0
  - debugpy=1.5.1
  - entrypoints=0.4
  - executing=0.8.3
  - flit-core=3.8.0
  - freetype=2.12.1
  - giflib=5.2.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - intel-openmp=2023.1.0
  - ipykernel=6.19.2
  - ipython=8.8.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.2.56
  - libcurand-dev=10.3.2.56
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - nest-asyncio=1.5.6
  - numpy-base=1.24.3
  - openssl=1.1.1t
  - packaging=23.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pywin32=305
  - setuptools=66.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.7.1
  - typing_extensions=4.5.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - audioread==3.0.0
    - chardet==5.1.0
    - charset-normalizer==3.1.0
    - contourpy==1.0.7
    - cycler==0.11.0
    - decorator==4.4.2
    - filelock==3.10.4
    - fonttools==4.39.0
    - ftfy==6.1.1
    - imageio==2.26.0
    - imageio-ffmpeg==0.4.8
    - importlib-resources==5.12.0
    - joblib==1.2.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - kiwisolver==1.4.4
    - librosa==0.7.2
    - llvmlite==0.31.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - moviepy==1.0.0
    - mpmath==1.3.0
    - networkx==3.0
    - numpy==1.20.0
    - opencv-python==4.7.0.72
    - pandas==1.0.3
    - pillow==9.4.0
    - proglog==0.1.10
    - pyparsing==3.0.9
    - pytorch-ignite==0.3.0
    - pytz==2022.7.1
    - pyzmq==25.0.0
    - regex==2022.10.31
    - requests==2.28.2
    - resampy==0.3.1
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - simplejpeg==1.6.5
    - soundfile==0.12.1
    - termcolor==1.1.0
    - torch==2.0.0
    - torchaudio==2.0.0
    - torchfile==0.1.0
    - torchvision==0.15.1
    - tqdm==4.43.0
    - urllib3==1.26.14
    - visdom==0.1.8.9
    - websocket-client==1.5.1
    - wget==3.2
    - zipp==3.15.0
